<?php

use Illuminate\Database\Seeder;
use App\City;

class CityTableSeeder extends Seeder
{
    /**
     * Seed the application's database.
     *
     * @return void
     */
    public function run()
    {
        DB::table('cities')->delete();
        City::create(array('id' => 1, 'state_id' => 1, 'name' => 'Ayer Baloi'));
        City::create(array('id' => 2, 'state_id' => 1, 'name' => 'Ayer Hitam'));
        City::create(array('id' => 3, 'state_id' => 1, 'name' => 'Bakri'));
        City::create(array('id' => 4, 'state_id' => 1, 'name' => 'Batu Anam'));
        City::create(array('id' => 5, 'state_id' => 1, 'name' => 'Batu Pahat'));
        City::create(array('id' => 6, 'state_id' => 1, 'name' => 'Bekok'));
        City::create(array('id' => 7, 'state_id' => 1, 'name' => 'Benut'));
        City::create(array('id' => 8, 'state_id' => 1, 'name' => 'Bukit Gambir'));
        City::create(array('id' => 9, 'state_id' => 1, 'name' => 'Bukit Pasir'));
        City::create(array('id' => 10, 'state_id' => 1, 'name' => 'Chaah'));
        City::create(array('id' => 11, 'state_id' => 1, 'name' => 'Endau'));
        City::create(array('id' => 12, 'state_id' => 1, 'name' => 'Gelang Patah'));
        City::create(array('id' => 13, 'state_id' => 1, 'name' => 'Gerisek'));
        City::create(array('id' => 14, 'state_id' => 1, 'name' => 'Gugusan Taib Andak'));
        City::create(array('id' => 15, 'state_id' => 1, 'name' => 'Iskandar Puteri'));
        City::create(array('id' => 16, 'state_id' => 1, 'name' => 'Jementah'));
        City::create(array('id' => 17, 'state_id' => 1, 'name' => 'Johor Bahru'));
        City::create(array('id' => 18, 'state_id' => 1, 'name' => 'Kahang'));
        City::create(array('id' => 19, 'state_id' => 1, 'name' => 'Kampung Kenangan Tun Dr Ismail'));
        City::create(array('id' => 20, 'state_id' => 1, 'name' => 'Kluang'));
        City::create(array('id' => 21, 'state_id' => 1, 'name' => 'Kota Tinggi'));
        City::create(array('id' => 22, 'state_id' => 1, 'name' => 'Kukup'));
        City::create(array('id' => 23, 'state_id' => 1, 'name' => 'Kulai'));
        City::create(array('id' => 24, 'state_id' => 1, 'name' => 'Labis'));
        City::create(array('id' => 25, 'state_id' => 1, 'name' => 'Layang Layang'));
        City::create(array('id' => 26, 'state_id' => 1, 'name' => 'Masai'));
        City::create(array('id' => 27, 'state_id' => 1, 'name' => 'Mersing'));
        City::create(array('id' => 28, 'state_id' => 1, 'name' => 'Muar'));
        City::create(array('id' => 29, 'state_id' => 1, 'name' => 'Pagoh'));
        City::create(array('id' => 30, 'state_id' => 1, 'name' => 'Paloh'));
        City::create(array('id' => 31, 'state_id' => 1, 'name' => 'Panchor'));
        City::create(array('id' => 32, 'state_id' => 1, 'name' => 'Parit Jawa'));
        City::create(array('id' => 33, 'state_id' => 1, 'name' => 'Parit Raja'));
        City::create(array('id' => 34, 'state_id' => 1, 'name' => 'Parit Sulong'));
        City::create(array('id' => 35, 'state_id' => 1, 'name' => 'Pasir Gudang'));
        City::create(array('id' => 36, 'state_id' => 1, 'name' => 'Pekan Nanas'));
        City::create(array('id' => 37, 'state_id' => 1, 'name' => 'Pengerang'));
        City::create(array('id' => 38, 'state_id' => 1, 'name' => 'Permas Jaya'));
        City::create(array('id' => 39, 'state_id' => 1, 'name' => 'Plentong'));
        City::create(array('id' => 40, 'state_id' => 1, 'name' => 'Pontian'));
        City::create(array('id' => 41, 'state_id' => 1, 'name' => 'Rengam'));
        City::create(array('id' => 42, 'state_id' => 1, 'name' => 'Rengit'));
        City::create(array('id' => 43, 'state_id' => 1, 'name' => 'Segamat'));
        City::create(array('id' => 44, 'state_id' => 1, 'name' => 'Semerah'));
        City::create(array('id' => 45, 'state_id' => 1, 'name' => 'Senai'));
        City::create(array('id' => 46, 'state_id' => 1, 'name' => 'Senggarang'));
        City::create(array('id' => 47, 'state_id' => 1, 'name' => 'Senibong'));
        City::create(array('id' => 48, 'state_id' => 1, 'name' => 'Seri Gading'));
        City::create(array('id' => 49, 'state_id' => 1, 'name' => 'Setia Indah'));
        City::create(array('id' => 50, 'state_id' => 1, 'name' => 'Setia Tropika'));
        City::create(array('id' => 51, 'state_id' => 1, 'name' => 'Simpang Rengam'));
        City::create(array('id' => 52, 'state_id' => 1, 'name' => 'Skudai'));
        City::create(array('id' => 53, 'state_id' => 1, 'name' => 'Sungai Mati'));
        City::create(array('id' => 54, 'state_id' => 1, 'name' => 'Tampoi'));
        City::create(array('id' => 55, 'state_id' => 1, 'name' => 'Tangkak'));
        City::create(array('id' => 56, 'state_id' => 1, 'name' => 'Ulu Tiram'));
        City::create(array('id' => 57, 'state_id' => 1, 'name' => 'Yong Peng'));
        City::create(array('id' => 58, 'state_id' => 2, 'name' => 'Alor Setar'));
        City::create(array('id' => 59, 'state_id' => 2, 'name' => 'Ayer Hitam'));
        City::create(array('id' => 60, 'state_id' => 2, 'name' => 'Baling'));
        City::create(array('id' => 61, 'state_id' => 2, 'name' => 'Bandar Baharu'));
        City::create(array('id' => 62, 'state_id' => 2, 'name' => 'Bukit Kayu Hitam'));
        City::create(array('id' => 63, 'state_id' => 2, 'name' => 'Guar Chempedak'));
        City::create(array('id' => 64, 'state_id' => 2, 'name' => 'Gurun'));
        City::create(array('id' => 65, 'state_id' => 2, 'name' => 'Jitra'));
        City::create(array('id' => 66, 'state_id' => 2, 'name' => 'Karangan'));
        City::create(array('id' => 67, 'state_id' => 2, 'name' => 'Kepala Batas'));
        City::create(array('id' => 68, 'state_id' => 2, 'name' => 'Kodiang'));
        City::create(array('id' => 69, 'state_id' => 2, 'name' => 'Kota Sarang Semut'));
        City::create(array('id' => 70, 'state_id' => 2, 'name' => 'Kuala Kedah'));
        City::create(array('id' => 71, 'state_id' => 2, 'name' => 'Kuala Ketil'));
        City::create(array('id' => 72, 'state_id' => 2, 'name' => 'Kuala Muda'));
        City::create(array('id' => 73, 'state_id' => 2, 'name' => 'Kuala Nerang'));
        City::create(array('id' => 74, 'state_id' => 2, 'name' => 'Kubang Pasu'));
        City::create(array('id' => 75, 'state_id' => 2, 'name' => 'Kulim'));
        City::create(array('id' => 76, 'state_id' => 2, 'name' => 'Kupang'));
        City::create(array('id' => 77, 'state_id' => 2, 'name' => 'Lunas'));
        City::create(array('id' => 78, 'state_id' => 2, 'name' => 'Merbok'));
        City::create(array('id' => 79, 'state_id' => 2, 'name' => 'Padang Serai'));
        City::create(array('id' => 80, 'state_id' => 2, 'name' => 'Padang Terap'));
        City::create(array('id' => 81, 'state_id' => 2, 'name' => 'Pendang'));
        City::create(array('id' => 82, 'state_id' => 2, 'name' => 'Pokok Sena'));
        City::create(array('id' => 83, 'state_id' => 2, 'name' => 'Pulau Langkawi'));
        City::create(array('id' => 84, 'state_id' => 2, 'name' => 'Serdang'));
        City::create(array('id' => 85, 'state_id' => 2, 'name' => 'Sik'));
        City::create(array('id' => 86, 'state_id' => 2, 'name' => 'Simpang Empat'));
        City::create(array('id' => 87, 'state_id' => 2, 'name' => 'Sungai Petani'));
        City::create(array('id' => 88, 'state_id' => 2, 'name' => 'University Utara'));
        City::create(array('id' => 89, 'state_id' => 2, 'name' => 'Yan'));
        City::create(array('id' => 90, 'state_id' => 2, 'name' => 'Bedong'));
        City::create(array('id' => 91, 'state_id' => 2, 'name' => 'Langgar'));
        City::create(array('id' => 92, 'state_id' => 2, 'name' => 'Changloon'));
        City::create(array('id' => 93, 'state_id' => 3, 'name' => 'Ayer Lanas'));
        City::create(array('id' => 94, 'state_id' => 3, 'name' => 'Bachok'));
        City::create(array('id' => 95, 'state_id' => 3, 'name' => 'Cherang Ruku'));
        City::create(array('id' => 96, 'state_id' => 3, 'name' => 'Dabong'));
        City::create(array('id' => 97, 'state_id' => 3, 'name' => 'Gua Musang'));
        City::create(array('id' => 98, 'state_id' => 3, 'name' => 'Jeli'));
        City::create(array('id' => 99, 'state_id' => 3, 'name' => 'Kem Desa Pahwalan'));
        City::create(array('id' => 100, 'state_id' => 3, 'name' => 'Ketereh'));
        City::create(array('id' => 101, 'state_id' => 3, 'name' => 'Kota Bharu'));
        City::create(array('id' => 102, 'state_id' => 3, 'name' => 'Kuala Balah'));
        City::create(array('id' => 103, 'state_id' => 3, 'name' => 'Kuala Kerai'));
        City::create(array('id' => 104, 'state_id' => 3, 'name' => 'Machang'));
        City::create(array('id' => 105, 'state_id' => 3, 'name' => 'Melor'));
        City::create(array('id' => 106, 'state_id' => 3, 'name' => 'Pasir Mas'));
        City::create(array('id' => 107, 'state_id' => 3, 'name' => 'Pasir Puteh'));
        City::create(array('id' => 108, 'state_id' => 3, 'name' => 'Pulai Chondong'));
        City::create(array('id' => 109, 'state_id' => 3, 'name' => 'Rantau Panjang'));
        City::create(array('id' => 110, 'state_id' => 3, 'name' => 'Selising'));
        City::create(array('id' => 111, 'state_id' => 3, 'name' => 'Tanah Merah'));
        City::create(array('id' => 112, 'state_id' => 3, 'name' => 'Tawang'));
        City::create(array('id' => 113, 'state_id' => 3, 'name' => 'Temangan'));
        City::create(array('id' => 114, 'state_id' => 3, 'name' => 'Tumpat'));
        City::create(array('id' => 115, 'state_id' => 3, 'name' => 'Wakaf Baru'));
        City::create(array('id' => 116, 'state_id' => 3, 'name' => 'Kok Lanas'));
        City::create(array('id' => 117, 'state_id' => 3, 'name' => 'Kubang Kerian'));
        City::create(array('id' => 118, 'state_id' => 4, 'name' => 'Ampang Hilir'));
        City::create(array('id' => 119, 'state_id' => 4, 'name' => 'Bandar Damai Perdana'));
        City::create(array('id' => 120, 'state_id' => 4, 'name' => 'Bandar Menjalara'));
        City::create(array('id' => 121, 'state_id' => 4, 'name' => 'Bandar Tasik Selatan'));
        City::create(array('id' => 122, 'state_id' => 4, 'name' => 'Bangsar'));
        City::create(array('id' => 123, 'state_id' => 4, 'name' => 'Bangsar South'));
        City::create(array('id' => 124, 'state_id' => 4, 'name' => 'Batu'));
        City::create(array('id' => 125, 'state_id' => 4, 'name' => 'Brickfields'));
        City::create(array('id' => 126, 'state_id' => 4, 'name' => 'Bukit Bintang'));
        City::create(array('id' => 127, 'state_id' => 4, 'name' => 'Bukit Jalil'));
        City::create(array('id' => 128, 'state_id' => 4, 'name' => 'Bukit Ledang'));
        City::create(array('id' => 129, 'state_id' => 4, 'name' => 'Bukit Persekutuan'));
        City::create(array('id' => 130, 'state_id' => 4, 'name' => 'Bukit Tunku'));
        City::create(array('id' => 131, 'state_id' => 4, 'name' => 'Cheras'));
        City::create(array('id' => 132, 'state_id' => 4, 'name' => 'City Centre'));
        City::create(array('id' => 133, 'state_id' => 4, 'name' => 'Country Heights'));
        City::create(array('id' => 134, 'state_id' => 4, 'name' => 'Country Heights Damansara'));
        City::create(array('id' => 135, 'state_id' => 4, 'name' => 'Damansara'));
        City::create(array('id' => 136, 'state_id' => 4, 'name' => 'Damansara Heights'));
        City::create(array('id' => 137, 'state_id' => 4, 'name' => 'Desa Pandan'));
        City::create(array('id' => 138, 'state_id' => 4, 'name' => 'Desa ParkCity'));
        City::create(array('id' => 139, 'state_id' => 4, 'name' => 'Desa Petaling'));
        City::create(array('id' => 140, 'state_id' => 4, 'name' => 'Gombak'));
        City::create(array('id' => 141, 'state_id' => 4, 'name' => 'Jalan Ampang'));
        City::create(array('id' => 142, 'state_id' => 4, 'name' => 'Jalan Ipoh'));
        City::create(array('id' => 143, 'state_id' => 4, 'name' => 'Jalan Kuching'));
        City::create(array('id' => 144, 'state_id' => 4, 'name' => 'Jalan Sultan Ismail'));
        City::create(array('id' => 145, 'state_id' => 4, 'name' => 'Jinjang'));
        City::create(array('id' => 146, 'state_id' => 4, 'name' => 'Kenny Hills'));
        City::create(array('id' => 147, 'state_id' => 4, 'name' => 'Kepong'));
        City::create(array('id' => 148, 'state_id' => 4, 'name' => 'Keramat'));
        City::create(array('id' => 149, 'state_id' => 4, 'name' => 'KL City'));
        City::create(array('id' => 150, 'state_id' => 4, 'name' => 'KL Sentral'));
        City::create(array('id' => 151, 'state_id' => 4, 'name' => 'KLCC'));
        City::create(array('id' => 152, 'state_id' => 4, 'name' => 'Kuchai Lama'));
        City::create(array('id' => 153, 'state_id' => 4, 'name' => 'Mid Valley City'));
        City::create(array('id' => 154, 'state_id' => 4, 'name' => 'Mont Kiara'));
        City::create(array('id' => 155, 'state_id' => 4, 'name' => 'Old Klang Road'));
        City::create(array('id' => 156, 'state_id' => 4, 'name' => 'OUG'));
        City::create(array('id' => 157, 'state_id' => 4, 'name' => 'Pandan Indah'));
        City::create(array('id' => 158, 'state_id' => 4, 'name' => 'Pandan Jaya'));
        City::create(array('id' => 159, 'state_id' => 4, 'name' => 'Pandan Perdana'));
        City::create(array('id' => 160, 'state_id' => 4, 'name' => 'Pantai'));
        City::create(array('id' => 161, 'state_id' => 4, 'name' => 'Pekan Batu'));
        City::create(array('id' => 162, 'state_id' => 4, 'name' => 'Puchong'));
        City::create(array('id' => 163, 'state_id' => 4, 'name' => 'Salak Selatan'));
        City::create(array('id' => 164, 'state_id' => 4, 'name' => 'Segambut'));
        City::create(array('id' => 165, 'state_id' => 4, 'name' => 'Sentul'));
        City::create(array('id' => 166, 'state_id' => 4, 'name' => 'Seputeh'));
        City::create(array('id' => 167, 'state_id' => 4, 'name' => 'Serdang'));
        City::create(array('id' => 168, 'state_id' => 4, 'name' => 'Setapak'));
        City::create(array('id' => 169, 'state_id' => 4, 'name' => 'Setia Eco Park'));
        City::create(array('id' => 170, 'state_id' => 4, 'name' => 'Setiawangsa'));
        City::create(array('id' => 171, 'state_id' => 4, 'name' => 'Solaris Dutamas'));
        City::create(array('id' => 172, 'state_id' => 4, 'name' => 'Sri Damansara'));
        City::create(array('id' => 173, 'state_id' => 4, 'name' => 'Sri Hartamas'));
        City::create(array('id' => 174, 'state_id' => 4, 'name' => 'Sri Petaling'));
        City::create(array('id' => 175, 'state_id' => 4, 'name' => 'Sungai Besi'));
        City::create(array('id' => 176, 'state_id' => 4, 'name' => 'Sungai Penchala'));
        City::create(array('id' => 177, 'state_id' => 4, 'name' => 'Taman Desa'));
        City::create(array('id' => 178, 'state_id' => 4, 'name' => 'Taman Duta'));
        City::create(array('id' => 179, 'state_id' => 4, 'name' => 'Taman Melawati'));
        City::create(array('id' => 180, 'state_id' => 4, 'name' => 'Taman Permata'));
        City::create(array('id' => 181, 'state_id' => 4, 'name' => 'Taman Tun Dr Ismail'));
        City::create(array('id' => 182, 'state_id' => 4, 'name' => 'Titiwangsa'));
        City::create(array('id' => 183, 'state_id' => 4, 'name' => 'TPM'));
        City::create(array('id' => 184, 'state_id' => 4, 'name' => 'Wangsa Maju'));
        City::create(array('id' => 185, 'state_id' => 5, 'name' => 'Batu Arang'));
        City::create(array('id' => 186, 'state_id' => 5, 'name' => 'Batu Manikar'));
        City::create(array('id' => 187, 'state_id' => 5, 'name' => 'Bebuloh'));
        City::create(array('id' => 188, 'state_id' => 5, 'name' => 'Belukut'));
        City::create(array('id' => 189, 'state_id' => 5, 'name' => 'Bukit Kalam'));
        City::create(array('id' => 190, 'state_id' => 5, 'name' => 'Bukit Kuda'));
        City::create(array('id' => 191, 'state_id' => 5, 'name' => 'Durian Tunjung'));
        City::create(array('id' => 192, 'state_id' => 5, 'name' => 'Ganggarak / Merinding'));
        City::create(array('id' => 193, 'state_id' => 5, 'name' => 'Gersik / Saguking / Jawa / Parit'));
        City::create(array('id' => 194, 'state_id' => 5, 'name' => 'Kilan / Kilan Pulau Akar'));
        City::create(array('id' => 195, 'state_id' => 5, 'name' => 'Lajau'));
        City::create(array('id' => 196, 'state_id' => 5, 'name' => 'Layang-Layangan'));
        City::create(array('id' => 197, 'state_id' => 5, 'name' => 'Lubok Temiang'));
        City::create(array('id' => 198, 'state_id' => 5, 'name' => 'Nagalang / Kerupang'));
        City::create(array('id' => 199, 'state_id' => 5, 'name' => 'Pantai'));
        City::create(array('id' => 200, 'state_id' => 5, 'name' => 'Patau-Patau 1'));
        City::create(array('id' => 201, 'state_id' => 5, 'name' => 'Patau-Patau 2'));
        City::create(array('id' => 202, 'state_id' => 5, 'name' => 'Pohon Batu'));
        City::create(array('id' => 203, 'state_id' => 5, 'name' => 'Rancha-Rancha'));
        City::create(array('id' => 204, 'state_id' => 5, 'name' => 'Sungai Bedaun'));
        City::create(array('id' => 205, 'state_id' => 5, 'name' => 'Sungai Bangat'));
        City::create(array('id' => 206, 'state_id' => 5, 'name' => 'Sungai Buton'));
        City::create(array('id' => 207, 'state_id' => 5, 'name' => 'Sungai Keling'));
        City::create(array('id' => 208, 'state_id' => 5, 'name' => 'Sungai Lada'));
        City::create(array('id' => 209, 'state_id' => 5, 'name' => 'Sungai Labu'));
        City::create(array('id' => 210, 'state_id' => 5, 'name' => 'Sungai Miri / Pagar'));
        City::create(array('id' => 211, 'state_id' => 5, 'name' => 'Tanjung Aru'));
        City::create(array('id' => 212, 'state_id' => 6, 'name' => 'Alor Gajah'));
        City::create(array('id' => 213, 'state_id' => 6, 'name' => 'Asahan'));
        City::create(array('id' => 214, 'state_id' => 6, 'name' => 'Ayer Keroh'));
        City::create(array('id' => 215, 'state_id' => 6, 'name' => 'Bandar Hilir'));
        City::create(array('id' => 216, 'state_id' => 6, 'name' => 'Batu Berendam'));
        City::create(array('id' => 217, 'state_id' => 6, 'name' => 'Bemban'));
        City::create(array('id' => 218, 'state_id' => 6, 'name' => 'Bukit Beruang'));
        City::create(array('id' => 219, 'state_id' => 6, 'name' => 'Durian Tunggal'));
        City::create(array('id' => 220, 'state_id' => 6, 'name' => 'Jasin'));
        City::create(array('id' => 221, 'state_id' => 6, 'name' => 'Kuala Linggi'));
        City::create(array('id' => 222, 'state_id' => 6, 'name' => 'Kuala Sungai Baru'));
        City::create(array('id' => 223, 'state_id' => 6, 'name' => 'Lubok China'));
        City::create(array('id' => 224, 'state_id' => 6, 'name' => 'Masjid Tanah'));
        City::create(array('id' => 225, 'state_id' => 6, 'name' => 'Melaka Tengah'));
        City::create(array('id' => 226, 'state_id' => 6, 'name' => 'Merlimau'));
        City::create(array('id' => 227, 'state_id' => 6, 'name' => 'Selandar'));
        City::create(array('id' => 228, 'state_id' => 6, 'name' => 'Sungai Rambai'));
        City::create(array('id' => 229, 'state_id' => 6, 'name' => 'Sungai Udang'));
        City::create(array('id' => 230, 'state_id' => 6, 'name' => 'Tanjong Kling'));
        City::create(array('id' => 231, 'state_id' => 6, 'name' => 'Ujong Pasir'));
        City::create(array('id' => 232, 'state_id' => 7, 'name' => 'Bahau'));
        City::create(array('id' => 233, 'state_id' => 7, 'name' => 'Bandar Baru Serting'));
        City::create(array('id' => 234, 'state_id' => 7, 'name' => 'Batang Melaka'));
        City::create(array('id' => 235, 'state_id' => 7, 'name' => 'Batu Kikir'));
        City::create(array('id' => 236, 'state_id' => 7, 'name' => 'Gemas'));
        City::create(array('id' => 237, 'state_id' => 7, 'name' => 'Gemencheh'));
        City::create(array('id' => 238, 'state_id' => 7, 'name' => 'Jelebu'));
        City::create(array('id' => 239, 'state_id' => 7, 'name' => 'Jempol'));
        City::create(array('id' => 240, 'state_id' => 7, 'name' => 'Johol'));
        City::create(array('id' => 241, 'state_id' => 7, 'name' => 'Juasseh'));
        City::create(array('id' => 242, 'state_id' => 7, 'name' => 'Kota'));
        City::create(array('id' => 243, 'state_id' => 7, 'name' => 'Kuala Klawang'));
        City::create(array('id' => 244, 'state_id' => 7, 'name' => 'Kuala Pilah'));
        City::create(array('id' => 245, 'state_id' => 7, 'name' => 'Labu'));
        City::create(array('id' => 246, 'state_id' => 7, 'name' => 'Lenggeng'));
        City::create(array('id' => 247, 'state_id' => 7, 'name' => 'Linggi'));
        City::create(array('id' => 248, 'state_id' => 7, 'name' => 'Mantin'));
        City::create(array('id' => 249, 'state_id' => 7, 'name' => 'Nilai'));
        City::create(array('id' => 250, 'state_id' => 7, 'name' => 'Pasir Panjang'));
        City::create(array('id' => 251, 'state_id' => 7, 'name' => 'Pedas'));
        City::create(array('id' => 252, 'state_id' => 7, 'name' => 'Port Dickson'));
        City::create(array('id' => 253, 'state_id' => 7, 'name' => 'Rantau'));
        City::create(array('id' => 254, 'state_id' => 7, 'name' => 'Rembau'));
        City::create(array('id' => 255, 'state_id' => 7, 'name' => 'Rompin'));
        City::create(array('id' => 256, 'state_id' => 7, 'name' => 'Senawang'));
        City::create(array('id' => 257, 'state_id' => 7, 'name' => 'Seremban'));
        City::create(array('id' => 258, 'state_id' => 7, 'name' => 'Siliau'));
        City::create(array('id' => 259, 'state_id' => 7, 'name' => 'Simpang Durian'));
        City::create(array('id' => 260, 'state_id' => 7, 'name' => 'Simpang Pertang'));
        City::create(array('id' => 261, 'state_id' => 7, 'name' => 'Sri Menanti'));
        City::create(array('id' => 262, 'state_id' => 7, 'name' => 'Si Rusa'));
        City::create(array('id' => 263, 'state_id' => 7, 'name' => 'Tampin'));
        City::create(array('id' => 264, 'state_id' => 7, 'name' => 'Tanjong Ipoh'));
        City::create(array('id' => 265, 'state_id' => 8, 'name' => 'Balok'));
        City::create(array('id' => 266, 'state_id' => 8, 'name' => 'Bandar Pusat Jengka'));
        City::create(array('id' => 267, 'state_id' => 8, 'name' => 'Bandar Tun Abdul Razak'));
        City::create(array('id' => 268, 'state_id' => 8, 'name' => 'Benta'));
        City::create(array('id' => 269, 'state_id' => 8, 'name' => 'Bentong'));
        City::create(array('id' => 270, 'state_id' => 8, 'name' => 'Bera'));
        City::create(array('id' => 271, 'state_id' => 8, 'name' => 'Brinchang'));
        City::create(array('id' => 272, 'state_id' => 8, 'name' => 'Bukit Fraser'));
        City::create(array('id' => 273, 'state_id' => 8, 'name' => 'Cameron Highlands'));
        City::create(array('id' => 274, 'state_id' => 8, 'name' => 'Chenor'));
        City::create(array('id' => 275, 'state_id' => 8, 'name' => 'Daerah Rompin'));
        City::create(array('id' => 276, 'state_id' => 8, 'name' => 'Damak'));
        City::create(array('id' => 277, 'state_id' => 8, 'name' => 'Dong'));
        City::create(array('id' => 278, 'state_id' => 8, 'name' => 'Genting Highlands'));
        City::create(array('id' => 279, 'state_id' => 8, 'name' => 'Jerantut'));
        City::create(array('id' => 280, 'state_id' => 8, 'name' => 'Karak'));
        City::create(array('id' => 281, 'state_id' => 8, 'name' => 'Kuala Lipis'));
        City::create(array('id' => 282, 'state_id' => 8, 'name' => 'Kuala Rompin'));
        City::create(array('id' => 283, 'state_id' => 8, 'name' => 'Kuantan'));
        City::create(array('id' => 284, 'state_id' => 8, 'name' => 'Lanchang'));
        City::create(array('id' => 285, 'state_id' => 8, 'name' => 'Lurah Bilut'));
        City::create(array('id' => 286, 'state_id' => 8, 'name' => 'Maran'));
        City::create(array('id' => 287, 'state_id' => 8, 'name' => 'Mengkarak'));
        City::create(array('id' => 288, 'state_id' => 8, 'name' => 'Mentakab'));
        City::create(array('id' => 289, 'state_id' => 8, 'name' => 'Muadzam Shah'));
        City::create(array('id' => 290, 'state_id' => 8, 'name' => 'Padang Tengku'));
        City::create(array('id' => 291, 'state_id' => 8, 'name' => 'Pekan'));
        City::create(array('id' => 292, 'state_id' => 8, 'name' => 'Raub'));
        City::create(array('id' => 293, 'state_id' => 8, 'name' => 'Ringlet'));
        City::create(array('id' => 294, 'state_id' => 8, 'name' => 'Rompin'));
        City::create(array('id' => 295, 'state_id' => 8, 'name' => 'Sega'));
        City::create(array('id' => 296, 'state_id' => 8, 'name' => "Sungai Koyan"));
        City::create(array('id' => 297, 'state_id' => 8, 'name' => "Sungai Lembing"));
        City::create(array('id' => 298, 'state_id' => 8, 'name' => "Sungai Ruan"));
        City::create(array('id' => 299, 'state_id' => 8, 'name' => "Tanah Rata"));
        City::create(array('id' => 300, 'state_id' => 8, 'name' => "Temerloh"));
        City::create(array('id' => 301, 'state_id' => 8, 'name' => "Triang"));
        City::create(array('id' => 302, 'state_id' => 9, 'name' => "Air Tawar"));
        City::create(array('id' => 303, 'state_id' => 9, 'name' => "Alma"));
        City::create(array('id' => 304, 'state_id' => 9, 'name' => "Ayer Itam"));
        City::create(array('id' => 305, 'state_id' => 9, 'name' => "Bagan Ajam"));
        City::create(array('id' => 306, 'state_id' => 9, 'name' => "Bagan Jermal"));
        City::create(array('id' => 307, 'state_id' => 9, 'name' => "Bagan Lalang"));
        City::create(array('id' => 308, 'state_id' => 9, 'name' => "Balik Pulau"));
        City::create(array('id' => 309, 'state_id' => 9, 'name' => "Bandar Perda"));
        City::create(array('id' => 310, 'state_id' => 9, 'name' => "Batu Ferringhi"));
        City::create(array('id' => 311, 'state_id' => 9, 'name' => "Batu Kawan"));
        City::create(array('id' => 312, 'state_id' => 9, 'name' => "Batu Maung"));
        City::create(array('id' => 313, 'state_id' => 9, 'name' => "Batu Uban"));
        City::create(array('id' => 314, 'state_id' => 9, 'name' => "Bayan Baru"));
        City::create(array('id' => 315, 'state_id' => 9, 'name' => "Bayan Lepas"));
        City::create(array('id' => 316, 'state_id' => 9, 'name' => "Berapit"));
        City::create(array('id' => 317, 'state_id' => 9, 'name' => "Bertam"));
        City::create(array('id' => 318, 'state_id' => 9, 'name' => "Bukit Dumbar"));
        City::create(array('id' => 319, 'state_id' => 9, 'name' => "Bukit Jambul"));
        City::create(array('id' => 320, 'state_id' => 9, 'name' => "Bukit Mertajam"));
        City::create(array('id' => 321, 'state_id' => 9, 'name' => "Bukit Minyak"));
        City::create(array('id' => 322, 'state_id' => 9, 'name' => "Bukit Tambun"));
        City::create(array('id' => 323, 'state_id' => 9, 'name' => "Bukit Tengah"));
        City::create(array('id' => 324, 'state_id' => 9, 'name' => "Butterworth"));
        City::create(array('id' => 325, 'state_id' => 9, 'name' => "Gelugor"));
        City::create(array('id' => 326, 'state_id' => 9, 'name' => "Georgetown"));
        City::create(array('id' => 327, 'state_id' => 9, 'name' => "Gertak Sangul"));
        City::create(array('id' => 328, 'state_id' => 9, 'name' => "Greenlane"));
        City::create(array('id' => 329, 'state_id' => 9, 'name' => "Jawi"));
        City::create(array('id' => 330, 'state_id' => 9, 'name' => "Jelutong"));
        City::create(array('id' => 331, 'state_id' => 9, 'name' => "Juru"));
        City::create(array('id' => 332, 'state_id' => 9, 'name' => "Kepala Batas"));
        City::create(array('id' => 333, 'state_id' => 9, 'name' => "Kubang Semang"));
        City::create(array('id' => 334, 'state_id' => 9, 'name' => "Mak Mandin"));
        City::create(array('id' => 335, 'state_id' => 9, 'name' => "Minden Heights"));
        City::create(array('id' => 336, 'state_id' => 9, 'name' => "Nibong Tebal"));
        City::create(array('id' => 337, 'state_id' => 9, 'name' => "Pauh Jaya"));
        City::create(array('id' => 338, 'state_id' => 9, 'name' => "Paya Terubong"));
        City::create(array('id' => 339, 'state_id' => 9, 'name' => "Penaga"));
        City::create(array('id' => 340, 'state_id' => 9, 'name' => "Penang Hill"));
        City::create(array('id' => 341, 'state_id' => 9, 'name' => "Penanti"));
        City::create(array('id' => 342, 'state_id' => 9, 'name' => "Perai"));
        City::create(array('id' => 343, 'state_id' => 9, 'name' => "Permatang Kuching"));
        City::create(array('id' => 344, 'state_id' => 9, 'name' => "Permatang Pauh"));
        City::create(array('id' => 345, 'state_id' => 9, 'name' => "Permatang Tinggi"));
        City::create(array('id' => 346, 'state_id' => 9, 'name' => "Persiaran Gurney"));
        City::create(array('id' => 347, 'state_id' => 9, 'name' => "Prai"));
        City::create(array('id' => 348, 'state_id' => 9, 'name' => "Pulau Betong"));
        City::create(array('id' => 349, 'state_id' => 9, 'name' => "Pulau Tikus"));
        City::create(array('id' => 350, 'state_id' => 9, 'name' => "Raja Uda"));
        City::create(array('id' => 351, 'state_id' => 9, 'name' => "Relau"));
        City::create(array('id' => 352, 'state_id' => 9, 'name' => "Scotland"));
        City::create(array('id' => 353, 'state_id' => 9, 'name' => "Seberang Jaya"));
        City::create(array('id' => 354, 'state_id' => 9, 'name' => "Seberang Perai"));
        City::create(array('id' => 355, 'state_id' => 9, 'name' => "Simpang Ampat"));
        City::create(array('id' => 356, 'state_id' => 9, 'name' => "Sungai Ara"));
        City::create(array('id' => 357, 'state_id' => 9, 'name' => "Sungai Bakap"));
        City::create(array('id' => 358, 'state_id' => 9, 'name' => "Sungai Dua"));
        City::create(array('id' => 359, 'state_id' => 9, 'name' => "Sungai Jawi"));
        City::create(array('id' => 360, 'state_id' => 9, 'name' => "Sungai Nibong"));
        City::create(array('id' => 361, 'state_id' => 9, 'name' => "Sungai Pinang"));
        City::create(array('id' => 362, 'state_id' => 9, 'name' => "Tanjong Tokong"));
        City::create(array('id' => 363, 'state_id' => 9, 'name' => "Tanjung Bungah"));
        City::create(array('id' => 364, 'state_id' => 9, 'name' => "Tasek Gelugor"));
        City::create(array('id' => 365, 'state_id' => 9, 'name' => "Teluk Bahang"));
        City::create(array('id' => 366, 'state_id' => 9, 'name' => "Teluk Kumbar"));
        City::create(array('id' => 367, 'state_id' => 9, 'name' => "USM"));
        City::create(array('id' => 368, 'state_id' => 9, 'name' => "Valdor"));
        City::create(array('id' => 369, 'state_id' => 10, 'name' => "Ayer Tawar"));
        City::create(array('id' => 370, 'state_id' => 10, 'name' => "Bagan Datoh"));
        City::create(array('id' => 371, 'state_id' => 10, 'name' => "Bagan Serai"));
        City::create(array('id' => 372, 'state_id' => 10, 'name' => "Batu Gajah"));
        City::create(array('id' => 373, 'state_id' => 10, 'name' => "Batu Kurau"));
        City::create(array('id' => 374, 'state_id' => 10, 'name' => "Behrang Stesen"));
        City::create(array('id' => 375, 'state_id' => 10, 'name' => "Beruas"));
        City::create(array('id' => 376, 'state_id' => 10, 'name' => "Bidor"));
        City::create(array('id' => 377, 'state_id' => 10, 'name' => "Bota"));
        City::create(array('id' => 378, 'state_id' => 10, 'name' => "Changkat Jering"));
        City::create(array('id' => 379, 'state_id' => 10, 'name' => "Changkat Keruing"));
        City::create(array('id' => 380, 'state_id' => 10, 'name' => "Chemor"));
        City::create(array('id' => 381, 'state_id' => 10, 'name' => "Chenderiang"));
        City::create(array('id' => 382, 'state_id' => 10, 'name' => "Chenderong Balai"));
        City::create(array('id' => 383, 'state_id' => 10, 'name' => "Chikus"));
        City::create(array('id' => 384, 'state_id' => 10, 'name' => "Enggor"));
        City::create(array('id' => 385, 'state_id' => 10, 'name' => "Gerik"));
        City::create(array('id' => 386, 'state_id' => 10, 'name' => "Gopeng"));
        City::create(array('id' => 387, 'state_id' => 10, 'name' => "Hutan Melintang"));
        City::create(array('id' => 388, 'state_id' => 10, 'name' => "Intan"));
        City::create(array('id' => 389, 'state_id' => 10, 'name' => "Ipoh"));
        City::create(array('id' => 390, 'state_id' => 10, 'name' => "Jeram"));
        City::create(array('id' => 391, 'state_id' => 10, 'name' => "Kampar"));
        City::create(array('id' => 392, 'state_id' => 10, 'name' => "Kampong Gajah"));
        City::create(array('id' => 393, 'state_id' => 10, 'name' => "Kampong Kepayang"));
        City::create(array('id' => 394, 'state_id' => 10, 'name' => "Kamunting"));
        City::create(array('id' => 395, 'state_id' => 10, 'name' => "Kuala Kangsar"));
        City::create(array('id' => 396, 'state_id' => 10, 'name' => "Kuala Kurau"));
        City::create(array('id' => 397, 'state_id' => 10, 'name' => "Kuala Sepatang"));
        City::create(array('id' => 398, 'state_id' => 10, 'name' => "Lahat"));
        City::create(array('id' => 399, 'state_id' => 10, 'name' => "Lambor Kanan"));
        City::create(array('id' => 400, 'state_id' => 10, 'name' => "Langkap"));
        City::create(array('id' => 401, 'state_id' => 10, 'name' => "Lenggong"));
        City::create(array('id' => 402, 'state_id' => 10, 'name' => "Lumut"));
        City::create(array('id' => 403, 'state_id' => 10, 'name' => "Malim Nawar"));
        City::create(array('id' => 404, 'state_id' => 10, 'name' => "Mambang Diawan"));
        City::create(array('id' => 405, 'state_id' => 10, 'name' => "Manong"));
        City::create(array('id' => 406, 'state_id' => 10, 'name' => "Matang"));
        City::create(array('id' => 407, 'state_id' => 10, 'name' => "Menglembu"));
        City::create(array('id' => 408, 'state_id' => 10, 'name' => "Padang Rengas"));
        City::create(array('id' => 409, 'state_id' => 10, 'name' => "Pangkor"));
        City::create(array('id' => 410, 'state_id' => 10, 'name' => "Pantai Remis"));
        City::create(array('id' => 411, 'state_id' => 10, 'name' => "Parit"));
        City::create(array('id' => 412, 'state_id' => 10, 'name' => "Parit Buntar"));
        City::create(array('id' => 413, 'state_id' => 10, 'name' => "Pengkalan Hulu"));
        City::create(array('id' => 414, 'state_id' => 10, 'name' => "Pusing"));
        City::create(array('id' => 415, 'state_id' => 10, 'name' => "Rantau Panjang"));
        City::create(array('id' => 416, 'state_id' => 10, 'name' => "Sauk"));
        City::create(array('id' => 417, 'state_id' => 10, 'name' => "Selama"));
        City::create(array('id' => 418, 'state_id' => 10, 'name' => "Selekoh"));
        City::create(array('id' => 419, 'state_id' => 10, 'name' => "Selinsing"));
        City::create(array('id' => 420, 'state_id' => 10, 'name' => "Semanggol"));
        City::create(array('id' => 421, 'state_id' => 10, 'name' => "Seri Iskandar"));
        City::create(array('id' => 422, 'state_id' => 10, 'name' => "Seri Manjong"));
        City::create(array('id' => 423, 'state_id' => 10, 'name' => "Simpang"));
        City::create(array('id' => 424, 'state_id' => 10, 'name' => "Sitiawan"));
        City::create(array('id' => 425, 'state_id' => 10, 'name' => "Slim River"));
        City::create(array('id' => 426, 'state_id' => 10, 'name' => "Sungai Siput"));
        City::create(array('id' => 427, 'state_id' => 10, 'name' => "Sungai Sumun"));
        City::create(array('id' => 428, 'state_id' => 10, 'name' => "Sungkai"));
        City::create(array('id' => 429, 'state_id' => 10, 'name' => "Taiping"));
        City::create(array('id' => 430, 'state_id' => 10, 'name' => "Tanjong Piandang"));
        City::create(array('id' => 431, 'state_id' => 10, 'name' => "Tanjong Rambutan"));
        City::create(array('id' => 432, 'state_id' => 10, 'name' => "Tanjong Tualang"));
        City::create(array('id' => 433, 'state_id' => 10, 'name' => "Tanjung Malim"));
        City::create(array('id' => 434, 'state_id' => 10, 'name' => "Tapah"));
        City::create(array('id' => 435, 'state_id' => 10, 'name' => "Teluk Intan"));
        City::create(array('id' => 436, 'state_id' => 10, 'name' => "Temoh"));
        City::create(array('id' => 437, 'state_id' => 10, 'name' => "TLDM Lumut"));
        City::create(array('id' => 438, 'state_id' => 10, 'name' => "Trolak"));
        City::create(array('id' => 439, 'state_id' => 10, 'name' => "Trong"));
        City::create(array('id' => 440, 'state_id' => 10, 'name' => "Tronoh"));
        City::create(array('id' => 441, 'state_id' => 10, 'name' => "Ulu Bernam"));
        City::create(array('id' => 442, 'state_id' => 10, 'name' => "Ulu Kinta"));
        City::create(array('id' => 443, 'state_id' => 11, 'name' => "Arau"));
        City::create(array('id' => 444, 'state_id' => 11, 'name' => "Kaki Bukit"));
        City::create(array('id' => 445, 'state_id' => 11, 'name' => "Kangar"));
        City::create(array('id' => 446, 'state_id' => 11, 'name' => "Kuala Perlis"));
        City::create(array('id' => 447, 'state_id' => 11, 'name' => "Padang Besar"));
        City::create(array('id' => 448, 'state_id' => 11, 'name' => "Pauh"));
        City::create(array('id' => 449, 'state_id' => 11, 'name' => "Simpang Ampat"));
        City::create(array('id' => 450, 'state_id' => 12, 'name' => "Putrajaya"));
        City::create(array('id' => 451, 'state_id' => 13, 'name' => "Beaufort"));
        City::create(array('id' => 452, 'state_id' => 13, 'name' => "Beluran"));
        City::create(array('id' => 453, 'state_id' => 13, 'name' => "Bongawan"));
        City::create(array('id' => 454, 'state_id' => 13, 'name' => "Keningau"));
        City::create(array('id' => 455, 'state_id' => 13, 'name' => "Kota Belud"));
        City::create(array('id' => 456, 'state_id' => 13, 'name' => "Kota Kinabalu"));
        City::create(array('id' => 457, 'state_id' => 13, 'name' => "Kota Kinabatangan"));
        City::create(array('id' => 458, 'state_id' => 13, 'name' => "Kota Marudu"));
        City::create(array('id' => 459, 'state_id' => 13, 'name' => "Kuala Penyu"));
        City::create(array('id' => 460, 'state_id' => 13, 'name' => "Kudat"));
        City::create(array('id' => 461, 'state_id' => 13, 'name' => "Kunak"));
        City::create(array('id' => 462, 'state_id' => 13, 'name' => "Lahad Datu"));
        City::create(array('id' => 463, 'state_id' => 13, 'name' => "Likas"));
        City::create(array('id' => 464, 'state_id' => 13, 'name' => "Membakut"));
        City::create(array('id' => 465, 'state_id' => 13, 'name' => "Menumbok"));
        City::create(array('id' => 466, 'state_id' => 13, 'name' => "Nabawan"));
        City::create(array('id' => 467, 'state_id' => 13, 'name' => "Pamol"));
        City::create(array('id' => 468, 'state_id' => 13, 'name' => "Papar"));
        City::create(array('id' => 469, 'state_id' => 13, 'name' => "Penampang"));
        City::create(array('id' => 470, 'state_id' => 13, 'name' => "Pitas"));
        City::create(array('id' => 471, 'state_id' => 13, 'name' => "Putatan"));
        City::create(array('id' => 472, 'state_id' => 13, 'name' => "Ranau"));
        City::create(array('id' => 473, 'state_id' => 13, 'name' => "Sandakan"));
        City::create(array('id' => 474, 'state_id' => 13, 'name' => "Semporna"));
        City::create(array('id' => 475, 'state_id' => 13, 'name' => "Sipitang"));
        City::create(array('id' => 476, 'state_id' => 13, 'name' => "Tambunan"));
        City::create(array('id' => 477, 'state_id' => 13, 'name' => "Tamparuli"));
        City::create(array('id' => 478, 'state_id' => 13, 'name' => "Tawau"));
        City::create(array('id' => 479, 'state_id' => 13, 'name' => "Telupid"));
        City::create(array('id' => 480, 'state_id' => 13, 'name' => "Tenom"));
        City::create(array('id' => 481, 'state_id' => 13, 'name' => "Tuaran"));
        City::create(array('id' => 482, 'state_id' => 14, 'name' => "Asajaya"));
        City::create(array('id' => 483, 'state_id' => 14, 'name' => "Balingian"));
        City::create(array('id' => 484, 'state_id' => 14, 'name' => "Baram"));
        City::create(array('id' => 485, 'state_id' => 14, 'name' => "Bau"));
        City::create(array('id' => 486, 'state_id' => 14, 'name' => "Bekenu"));
        City::create(array('id' => 487, 'state_id' => 14, 'name' => "Belaga"));
        City::create(array('id' => 488, 'state_id' => 14, 'name' => "Belawai"));
        City::create(array('id' => 489, 'state_id' => 14, 'name' => "Betong"));
        City::create(array('id' => 490, 'state_id' => 14, 'name' => "Bintangor"));
        City::create(array('id' => 491, 'state_id' => 14, 'name' => "Bintulu"));
        City::create(array('id' => 492, 'state_id' => 14, 'name' => "Dalat"));
        City::create(array('id' => 493, 'state_id' => 14, 'name' => "Daro"));
        City::create(array('id' => 494, 'state_id' => 14, 'name' => "Debak"));
        City::create(array('id' => 495, 'state_id' => 14, 'name' => "Engkilili"));
        City::create(array('id' => 496, 'state_id' => 14, 'name' => "Julau"));
        City::create(array('id' => 497, 'state_id' => 14, 'name' => "Kabong"));
        City::create(array('id' => 498, 'state_id' => 14, 'name' => "Kanowit"));
        City::create(array('id' => 499, 'state_id' => 14, 'name' => "Kapit"));
        City::create(array('id' => 500, 'state_id' => 14, 'name' => "Kota Samarahan"));
        City::create(array('id' => 501, 'state_id' => 14, 'name' => "Kuching"));
        City::create(array('id' => 502, 'state_id' => 14, 'name' => "Lawas"));
        City::create(array('id' => 503, 'state_id' => 14, 'name' => "Limbang"));
        City::create(array('id' => 504, 'state_id' => 14, 'name' => "Lingga"));
        City::create(array('id' => 505, 'state_id' => 14, 'name' => "Long Lama"));
        City::create(array('id' => 506, 'state_id' => 14, 'name' => "Lubok Antu"));
        City::create(array('id' => 507, 'state_id' => 14, 'name' => "Lundu"));
        City::create(array('id' => 508, 'state_id' => 14, 'name' => "Lutong"));
        City::create(array('id' => 509, 'state_id' => 14, 'name' => "Maradong"));
        City::create(array('id' => 510, 'state_id' => 14, 'name' => "Marudi"));
        City::create(array('id' => 511, 'state_id' => 14, 'name' => "Matu"));
        City::create(array('id' => 512, 'state_id' => 14, 'name' => "Miri"));
        City::create(array('id' => 513, 'state_id' => 14, 'name' => "Mukah"));
        City::create(array('id' => 514, 'state_id' => 14, 'name' => "Nanga Medamit"));
        City::create(array('id' => 515, 'state_id' => 14, 'name' => "Niah"));
        City::create(array('id' => 516, 'state_id' => 14, 'name' => "Pusa"));
        City::create(array('id' => 517, 'state_id' => 14, 'name' => "Roban"));
        City::create(array('id' => 518, 'state_id' => 14, 'name' => "Saratok"));
        City::create(array('id' => 519, 'state_id' => 14, 'name' => "Sarikei"));
        City::create(array('id' => 520, 'state_id' => 14, 'name' => "Sebauh"));
        City::create(array('id' => 521, 'state_id' => 14, 'name' => "Sebuyau"));
        City::create(array('id' => 522, 'state_id' => 14, 'name' => "Serian"));
        City::create(array('id' => 523, 'state_id' => 14, 'name' => "Sibu"));
        City::create(array('id' => 524, 'state_id' => 14, 'name' => "Simunjan"));
        City::create(array('id' => 525, 'state_id' => 14, 'name' => "Song"));
        City::create(array('id' => 526, 'state_id' => 14, 'name' => "Spaoh"));
        City::create(array('id' => 527, 'state_id' => 14, 'name' => "Sri Aman"));
        City::create(array('id' => 528, 'state_id' => 14, 'name' => "Sundar"));
        City::create(array('id' => 529, 'state_id' => 14, 'name' => "Tanjung Kidurong"));
        City::create(array('id' => 530, 'state_id' => 14, 'name' => "Tatau"));
        City::create(array('id' => 531, 'state_id' => 15, 'name' => "Alam Impian"));
        City::create(array('id' => 532, 'state_id' => 15, 'name' => "Aman Perdana"));
        City::create(array('id' => 533, 'state_id' => 15, 'name' => "Ambang Botanic"));
        City::create(array('id' => 534, 'state_id' => 15, 'name' => "Ampang"));
        City::create(array('id' => 535, 'state_id' => 15, 'name' => "Ara Damansara"));
        City::create(array('id' => 536, 'state_id' => 15, 'name' => "Balakong"));
        City::create(array('id' => 537, 'state_id' => 15, 'name' => "Bandar Botanic"));
        City::create(array('id' => 538, 'state_id' => 15, 'name' => "Bandar Bukit Raja"));
        City::create(array('id' => 539, 'state_id' => 15, 'name' => "Bandar Bukit Tinggi"));
        City::create(array('id' => 540, 'state_id' => 15, 'name' => "Bandar Kinrara"));
        City::create(array('id' => 541, 'state_id' => 15, 'name' => "Bandar Puteri Puchong"));
        City::create(array('id' => 542, 'state_id' => 15, 'name' => "Bandar Puteri Klang"));
        City::create(array('id' => 543, 'state_id' => 15, 'name' => "Bandar Saujana Putra"));
        City::create(array('id' => 544, 'state_id' => 15, 'name' => "Bandar Sungai Long"));
        City::create(array('id' => 545, 'state_id' => 15, 'name' => "Bandar Sunway"));
        City::create(array('id' => 546, 'state_id' => 15, 'name' => "Bandar Utama"));
        City::create(array('id' => 547, 'state_id' => 15, 'name' => "Bangi"));
        City::create(array('id' => 548, 'state_id' => 15, 'name' => "Banting"));
        City::create(array('id' => 549, 'state_id' => 15, 'name' => "Batang Berjuntai"));
        City::create(array('id' => 550, 'state_id' => 15, 'name' => "Batang Kali"));
        City::create(array('id' => 551, 'state_id' => 15, 'name' => "Batu Arang"));
        City::create(array('id' => 552, 'state_id' => 15, 'name' => "Batu Caves"));
        City::create(array('id' => 553, 'state_id' => 15, 'name' => "Beranang"));
        City::create(array('id' => 554, 'state_id' => 15, 'name' => "Bukit Antarabangsa"));
        City::create(array('id' => 555, 'state_id' => 15, 'name' => "Bukit Beruntung"));
        City::create(array('id' => 556, 'state_id' => 15, 'name' => "Bukit Jelutong"));
        City::create(array('id' => 557, 'state_id' => 15, 'name' => "Bukit Rahman Putra"));
        City::create(array('id' => 558, 'state_id' => 15, 'name' => "Bukit Rotan"));
        City::create(array('id' => 559, 'state_id' => 15, 'name' => "Bukit Subang"));
        City::create(array('id' => 560, 'state_id' => 15, 'name' => "Cheras"));
        City::create(array('id' => 561, 'state_id' => 15, 'name' => "Country Heights"));
        City::create(array('id' => 562, 'state_id' => 15, 'name' => "Cyberjaya"));
        City::create(array('id' => 563, 'state_id' => 15, 'name' => "Damansara Damai"));
        City::create(array('id' => 564, 'state_id' => 15, 'name' => "Damansara Intan"));
        City::create(array('id' => 565, 'state_id' => 15, 'name' => "Damansara Jaya"));
        City::create(array('id' => 566, 'state_id' => 15, 'name' => "Damansara Kim"));
        City::create(array('id' => 567, 'state_id' => 15, 'name' => "Damansara Perdana"));
        City::create(array('id' => 568, 'state_id' => 15, 'name' => "Damansara Utama"));
        City::create(array('id' => 569, 'state_id' => 15, 'name' => "Denai Alam"));
        City::create(array('id' => 570, 'state_id' => 15, 'name' => "Dengkil"));
        City::create(array('id' => 571, 'state_id' => 15, 'name' => "Glenmarie"));
        City::create(array('id' => 572, 'state_id' => 15, 'name' => "Gombak"));
        City::create(array('id' => 573, 'state_id' => 15, 'name' => "Hulu Langat"));
        City::create(array('id' => 574, 'state_id' => 15, 'name' => "Hulu Selangor"));
        City::create(array('id' => 575, 'state_id' => 15, 'name' => "Jenjarom"));
        City::create(array('id' => 576, 'state_id' => 15, 'name' => "Kajang"));
        City::create(array('id' => 577, 'state_id' => 15, 'name' => "Kapar"));
        City::create(array('id' => 578, 'state_id' => 15, 'name' => "Kayu Ara"));
        City::create(array('id' => 579, 'state_id' => 15, 'name' => "Kelana Jaya"));
        City::create(array('id' => 580, 'state_id' => 15, 'name' => "Kerling"));
        City::create(array('id' => 581, 'state_id' => 15, 'name' => "Klang"));
        City::create(array('id' => 582, 'state_id' => 15, 'name' => "Kota Damansara"));
        City::create(array('id' => 583, 'state_id' => 15, 'name' => "Kota Emerald"));
        City::create(array('id' => 584, 'state_id' => 15, 'name' => "Kota Kemuning"));
        City::create(array('id' => 585, 'state_id' => 15, 'name' => "Kuala Kubu Baru"));
        City::create(array('id' => 586, 'state_id' => 15, 'name' => "Kuala Langat"));
        City::create(array('id' => 587, 'state_id' => 15, 'name' => "Kuala Selangor"));
        City::create(array('id' => 588, 'state_id' => 15, 'name' => "Kuang"));
        City::create(array('id' => 589, 'state_id' => 15, 'name' => "Mutiara Damansara"));
        City::create(array('id' => 590, 'state_id' => 15, 'name' => "Petaling Jaya"));
        City::create(array('id' => 591, 'state_id' => 15, 'name' => "Port Klang"));
        City::create(array('id' => 592, 'state_id' => 15, 'name' => "Puchong"));
        City::create(array('id' => 593, 'state_id' => 15, 'name' => "Puchong South"));
        City::create(array('id' => 594, 'state_id' => 15, 'name' => "Pulau Indah (Pulau Lumut)"));
        City::create(array('id' => 595, 'state_id' => 15, 'name' => "Pulau Carey"));
        City::create(array('id' => 596, 'state_id' => 15, 'name' => "Pulau Ketam"));
        City::create(array('id' => 597, 'state_id' => 15, 'name' => "Puncak Alam"));
        City::create(array('id' => 598, 'state_id' => 15, 'name' => "Puncak Jalil"));
        City::create(array('id' => 599, 'state_id' => 15, 'name' => "Putra Heights"));
        City::create(array('id' => 600, 'state_id' => 15, 'name' => "Rasa"));
        City::create(array('id' => 601, 'state_id' => 15, 'name' => "Rawang"));
        City::create(array('id' => 602, 'state_id' => 15, 'name' => "Sabak Bernam"));
        City::create(array('id' => 603, 'state_id' => 15, 'name' => "Salak Tinggi"));
        City::create(array('id' => 604, 'state_id' => 15, 'name' => "Saujana"));
        City::create(array('id' => 605, 'state_id' => 15, 'name' => "Saujana Utama"));
        City::create(array('id' => 606, 'state_id' => 15, 'name' => "Sekinchan"));
        City::create(array('id' => 607, 'state_id' => 15, 'name' => "Selayang"));
        City::create(array('id' => 608, 'state_id' => 15, 'name' => "Semenyih"));
        City::create(array('id' => 609, 'state_id' => 15, 'name' => "Sepang"));
        City::create(array('id' => 610, 'state_id' => 15, 'name' => "Serdang"));
        City::create(array('id' => 611, 'state_id' => 15, 'name' => "Serendah"));
        City::create(array('id' => 612, 'state_id' => 15, 'name' => "Seri Kembangan"));
        City::create(array('id' => 613, 'state_id' => 15, 'name' => "Setia Alam"));
        City::create(array('id' => 614, 'state_id' => 15, 'name' => "Setia Eco Park"));
        City::create(array('id' => 615, 'state_id' => 15, 'name' => "Shah Alam"));
        City::create(array('id' => 616, 'state_id' => 15, 'name' => "SierraMas"));
        City::create(array('id' => 617, 'state_id' => 15, 'name' => "SS2"));
        City::create(array('id' => 618, 'state_id' => 15, 'name' => "Subang Bestari"));
        City::create(array('id' => 619, 'state_id' => 15, 'name' => "Subang Heights"));
        City::create(array('id' => 620, 'state_id' => 15, 'name' => "Subang Jaya"));
        City::create(array('id' => 621, 'state_id' => 15, 'name' => "Subang Perdana"));
        City::create(array('id' => 622, 'state_id' => 15, 'name' => "Sungai Ayer Tawar"));
        City::create(array('id' => 623, 'state_id' => 15, 'name' => "Sungai Besar"));
        City::create(array('id' => 624, 'state_id' => 15, 'name' => "Sungai Buloh"));
        City::create(array('id' => 625, 'state_id' => 15, 'name' => "Sungai Pelek"));
        City::create(array('id' => 626, 'state_id' => 15, 'name' => "Taman TTDI Jaya"));
        City::create(array('id' => 627, 'state_id' => 15, 'name' => "Tanjong Karang"));
        City::create(array('id' => 628, 'state_id' => 15, 'name' => "Tanjong Sepat"));
        City::create(array('id' => 629, 'state_id' => 15, 'name' => "Telok Panglima Garang"));
        City::create(array('id' => 630, 'state_id' => 15, 'name' => "Tropicana"));
        City::create(array('id' => 631, 'state_id' => 15, 'name' => "Ulu Klang"));
        City::create(array('id' => 632, 'state_id' => 15, 'name' => "USJ"));
        City::create(array('id' => 633, 'state_id' => 15, 'name' => "USJ Heights"));
        City::create(array('id' => 634, 'state_id' => 15, 'name' => "Valencia"));
        City::create(array('id' => 635, 'state_id' => 16, 'name' => "Besut"));
        City::create(array('id' => 636, 'state_id' => 16, 'name' => "Dungun"));
        City::create(array('id' => 637, 'state_id' => 16, 'name' => "Hulu Terengganu"));
        City::create(array('id' => 638, 'state_id' => 16, 'name' => "Kemaman"));
        City::create(array('id' => 639, 'state_id' => 16, 'name' => "Kuala Nerus"));
        City::create(array('id' => 640, 'state_id' => 16, 'name' => "Kuala Terengganu"));
        City::create(array('id' => 641, 'state_id' => 16, 'name' => "Marang"));
        City::create(array('id' => 642, 'state_id' => 16, 'name' => "Setiu"));
        $this->command->info('City table seeded');
    }
}
